apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-spring-fibonacci-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-spring-fibonacci
  template:
    metadata:
      labels:
        app: kube-spring-fibonacci
    spec:
      containers:
        - name: kube-spring-fibonacci-container
          image: davcd/kube-spring-fibonacci
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '512Mi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: kube-spring-fibonacci-service
  namespace: default
spec:
  selector:
    app: kube-spring-fibonacci
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: kube-spring-fibonacci-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-spring-fibonacci-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
   -  type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
